### ISSUE TITLE
[Feature] ; handling backend 

### ISSUE THREAD

**Issue by shiv-sk** [NodeJSEngineering/Node-Task-Queue-system#5]
adding backend and connecting with frontend 

i want create user model , task model , queue model and respective controllers 

features 
user - register , login , logout 
task - crud with priority like high , low , mid and task request and task assign
queue - implementing queue system with task (fifo)
role based access

description of queue (working)
a user can create a task and some other user can view when a user request to assign a task there is queue in game all request are stored in queue i the owner can accept or reject the request

**Comment by sunny7899** [comment]
go ahead @shiv-sk
